group:
    # All repos
    - files:
          # Misc
          - source: .gitignore
            dest: .gitignore
      repos: |
          dp-next/dp-next.github.io
          dp-next/.github
          dp-next/WP1-Communication
          dp-next/WP1-Management
          dp-next/WP2-Risk-Prediction
          dp-next/WP3-Heterogeneity
          dp-next/WP4-Intervention-Development

    # Specific repos
    - files:
          # Workflows
          - source: .github/workflows/add-to-board.yml
            dest: .github/workflows/add-to-board.yml

          # VS Code settings
          - source: .vscode/
            dest: .vscode/
            deleteOrphaned: true

      repos: |
          dp-next/dp-next.github.io
          dp-next/.github

    # Website repos
    - files:
          # Workflows
          - source: .github/workflows/build-website.yml
            dest: .github/workflows/build-website.yml

      repos: |
          dp-next/dp-next.github.io
