project:
  # TODO: Change to correct project type if using extensions
  type: book


book:
  title: "Better research in less time"
  site-url: "https://dp-next.github.io/wp1-ros/"
  repo-url: "https://github.com/dp-next/wp1-ros"
  repo-actions: [issue, edit, source]
  author:
    - name: "Luke W. Johnston"
      affiliation: "Steno Diabetes Center Aarhus"
      orcid: "0000-0003-4169-2616"
  date: last-modified
  body-header: |
    ::: {.callout-warning appearance="default" icon="true"}
    🚧 This website and documentation is still in very active development and
    evolving quickly, so content could undergo substantial changes at any time
    🚧
    :::
  search:
    location: "navbar"
    type: "textbox"
  navbar:
    pinned: true
  chapters:
    - href: index.qmd
      text: Welcome
    - part: Overview
      chapters:
        - motivation.qmd
        - strategy.qmd
        - risks.qmd
        - groups.qmd
        - roadmap.qmd
    - part: Design
      chapters:
        - index.qmd
        - patterns.qmd
        - practicals.qmd
        - naming.qmd
    - part: Decisions
      chapters:
        - decisions/index.qmd
        - decisions/why-r-python.qmd
    - part: Collaborating
      chapters:
        - collaborating/index.qmd
        - collaborating/project-management.qmd
        - collaborating/meetings.qmd
        - collaborating/dst.qmd
    - part: Contributing
      chapters:
        - contributing/index.qmd
  appendices:
    - CONTRIBUTING.md
    - href: LICENSE.md
      text: License
  tools:
    - icon: github
      href: "https://github.com/dp-next/wp1-ros"
      aria-label: "GitHub icon: Source repository"
    - icon: house
      href: https://dp-next.github.io
      aria-label: "House icon: DP-Next home page"
  page-footer:
    center:
      - text: "Licensed under CC BY 4.0"
        href: "LICENSE.md"

format:
  html:
    from: markdown+emoji
    toc: true

bibliography: references.bib
csl: vancouver.csl

metadata-files:
  - _metadata.yml
