---
format: gfm
metadata-files:
  - _metadata.yml
---

# {{< meta titles.short >}}

{{< include /includes/_badges.qmd >}}

> A guide on using reproducible and open scientific practices in the
> multi-center DP-Next project to do better research in less time and
> fewer resources.

This is work package 1 of the [DP-Next
project](https://dp-next.github.io/). The main part of this work package
1 involves incorporating reproducible and open science practices into
the workflow and output of the DP-Next project. A secondary part of this
work package is to develop a set of tools and practices that will help
the project achieve its goals in a more efficient manner through the use
of research operations, iterative project management, and a digital
infrastructure that supports the research. Hopefully that will translate
into more effective collaboration, communication, coordination, and
development of the project.

Check out the [website](https://dp-next.github.io/wp1-ros/) for this
work package for more information. For a list of changes made to the
content itself (not to files that support developing this guide), see
our [changelog](https://wp1-ros.github.io/wp1-ros/releases/) page.

We integrate and make heavy use of the work done in the [Seedcase
Project](https://seedcase-project.org).


::: callout-tip
This website repository was generated from the
[`template-website`](https://github.com/seedcase-project/template-website)
Seedcase template :tada:
:::

## Project files and folders

- `.copier-answers.yml`: Contains the answers you gave when copying the
  project from the template.
  **You should not modify this file directly.**
- `.cz.toml`:
  [Commitizen](https://commitizen-tools.github.io/commitizen/)
  configuration file for managing versions and changelogs.
- `.pre-commit-config.yaml`: [Pre-commit](https://pre-commit.com/)
  configuration file for managing and running checks before each commit.
- `.typos.toml`: [typos](https://github.com/crate-ci/typos) spell
  checker configuration file.
- `.zenodo.json`: Structured citation metadata for your project when
  archived on [Zenodo](https://zenodo.org/). This is used to add the
  metadata to Zenodo when a GitHub release has been uploaded to Zenodo.
- `justfile`: [`just`](https://just.systems/man/en/) configuration file
  for scripting project tasks.
- `.editorconfig`: Editor configuration file for
  [EditorConfig](https://editorconfig.org/) to maintain consistent
  coding styles across different editors and IDEs.
- `CHANGELOG.md`: Changelog file for tracking changes in the project.
- `CONTRIBUTING.md`: Guidelines for contributing to the project.
- `.github/`: Contains GitHub-specific files, such as issue and pull
  request templates, workflows,
  [dependabot](https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/dependabot-quickstart-guide)
  configuration, pull request templates, and a
  [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
  file.
- `_metadata.yml`: Quarto metadata file for the website, including
  information about the project, such as the titles and GitHub names.
- `_quarto.yml`: Quarto configuration file for the website, including
  settings for the website, such as the theme, navigation, and other
  options.
- `.rumdl.toml`: [rumdl](https://rumdl.dev) configuration file for
  formatting Markdown files in the project.

## Contributing

Check out our [contributing document](CONTRIBUTING.md) for information
on how to contribute to the project, including how to set up your
development environment.

Please note that this project is released with a
[Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in
this project you agree to abide by its terms.

::: content-hidden
<!-- TODO: Unhide when there are more contributors -->
### Contributors

{{< include /includes/_contributors.qmd >}}
:::

## Licensing

This project is licensed under the [CC-BY-4.0 License](LICENSE.md).

## Changelog

For a list of changes, see our [changelog](CHANGELOG.md) page.

::: content-hidden
## Citing

This project is part of the Seedcase Project, which is a collaborative
effort to create a framework for data management and analysis in
research. If you use this project in your work, please cite it as
follows:
:::
