---
title: "Roadmap"
description: General project planning, outputs, and Gantt charts for WP1.
---

This document covers the plan for Work Package 1. While the Gantt charts
display an overview of the project, the sections below on milestones and
deliverables provide more detailed information than what can be put on
the charts.

```{mermaid}
%%| file: images/gantt.mmd
%%| label: fig-gantt
%%| fig-cap: "Gantt chart showing some basic tasks, milestones, and deliverables for Work Package 1."
```

## Deliverables

### Reports

-   Consensus document on agreed upon processes and workflows between
    WPs
-   Research operational management practices and processes employed in
    a large-scale multi-centered project: Future uses of using modern
    approaches to team-based research
-   DP-Next as an open-access and secure Data Resource for broader
    re-use of collected data for researchers (using SDCA-developed,
    NNF-funded Seedcase software)
-   Challenges and lessons learned in applying modern research ops and
    data engineering to a large-scale, multi-center project

### Resources

-   Each center has resources and workflows for conducting reproducible
    and modern register-based research using the Danish registers
-   DP-Next data resource built from Seedcase software
-   DP-Next project website, with all (internal and external) knowledge
    generated, including all code and documentation

## Milestones

-   Setup project websites to host details and documents relevant to
    this project and it's WPs

-   Setup website to document and describe research operational
    practices used across Centers for easier sharing and onboarding

-   Open-source template Data Management Plan to use for WP3

-   Setup research data infrastructure that supports adhering to open
    FAIR practices for ease of internal and external sharing of data for
    WP3 (using software built from NNF-funded project from SDCA called
    Seedcase: https://seedcase-project.org/)

-   Open-source templates for building software package/app for risk
    prediction engine from WP2

## Sequence of outcomes

Nothing can be achieved immediately and everything takes time. By
following [our principles](design.qmd) of "start with what we do now"
and "make incremental and iterative improvements", the below is a
potential sequence of outcomes to get to where we'd like to be. These
are in order of what we'd like to achieve first to last, focusing on
achieving one outcome at a time. We'll add to this as we go along, and
update it as we've achieved each item.

### Collaboration

1.  Only use GitHub Issues for tasks, discussions, and general
    communication, so that all work is visible and tracked in one place.
2.  Always refer to the GitHub Project board for the current status of
    the project or individual work packages, so everyone is aware of the
    current state of things.
3.  Put all work package specific or DP-Next wide events or meetings
    into the shared calendar (via Teamup).
4.  Only use Discord and specific channels for work packages for
    communication and coordination.

### Contribution

1.  Put all content related to the project onto GitHub, at first at
    least as comments on GitHub Issues.
2.  Write files in only Markdown (if text).
3.  Write all code in R or Python.
4.  Have anything that isn't private/secret/admin as a public (open)
    GitHub repository.
5.  Include R or Python code into Markdown files (via Quarto).
6.  Write R or Python code within a reproducible pipeline framework
    (e.g. [targets](https://books.ropensci.org/targets/) for R).
7.  Generate anything that isn't private/secret/admin into websites.
