# DP-Next Publication Guidelines {#sec-publishing}

## Introduction

The purpose of this document is to establish an internal guideline for
publications and authorship based on the DP-Next project and related
subprojects. It also outlines the decision-making processes in relation
to publications and the responsibilities of authors and the DP-Next
Steering Committee (SC) in facilitating an optimal publication strategy
and an honest and transparent authorship policy.

## DP-Next publication mindset and overall process

According to the original project description to the Novo Nordisk
Foundation (<https://dp-next.github.io/>) and the collaboration
agreement (Section 12), DP-Next aims to work, collaborate, and publish
following the principles of open and reproducible science. This document
outlines in more detail how we operationalise these principles in
practice, and has the status of guideline. In case of any discrepancy or
conflict between this guideline and the collaboration agreement, the
text of the collaboration agreement has precedence. Any substantial
deviations from this guideline should be justified and approved by the
SC.

According to the collaboration agreement the SC is charged with
outlining and implementing the project's publication strategy. The main
aims of this strategy are:

- To jointly publish positive, negative and inconclusive results in
  international peer-reviewed scientific journals

- To work according to open and reproducible research practices

The sections below outline how these principles will be implemented in
practice; first at a general level and then including operational
details.

### General Open and Reproducible research practices

- All DP-Next publications/outputs should be published as Open Access
  publications, with a strong preference for:

  - The Green Open Access format
  - Publication agreements that do not require the transfer of copyright to publishers
  - Publication under a Creative Commons CC-BY license.

- All DP-Next publications should be accompanied by the following:

  - A synopsis of the proposed publication, including a defined aim/hypothesis, general methodological approach, required data, expected timeline, and proposed author list. This synopsis is only for internal use, and should be approved by the SC before any work on a specific analysis/paper starts (see below).
  - A detailed analysis protocol, published on an online repository such as Zenodo or OpenAIRE to obtain a Digital Object Identifier (DOI) and clearly establish a clear temporal sequence between definition of hypotheses/analytic approaches and analysis of data.
  - A publicly accessible repository on GitHub containing the detailed analytical code that generates the tables, graphs and figures included in the manuscript, as well as the full text of the manuscript, abstracts submitted to conferences and slides/posters that present the work, the synopsis and the protocol.
  - Preprints of substantial versions of the manuscript on online preprint servers such as arXiv or medRxiv.

### General authorship practices

Authorship of DP-Next publications should reflect a substantial, direct
contribution to the work presented in each paper. We aim to reflect the
Vancouver Guidelines (<https://www.icmje.org/icmje-recommendations.pdf>)
(ICMJE) for authorship, expanding on them to reflect non-traditional
research contributions. Non-traditional research contributions are
activities that contribute in a clear way to the creation of the
publication, such as improving data quality, developing software or
improving analysis code.

Author lists and orders will be established at the stage of definition
of the synopsis / analysis protocol. All who have contributed to DP-Next
who also qualify for co-authorship should be given the chance to become
co-author on papers relating to data that they have helped collect or
analyse. The SC will help to facilitate this by keeping an up to date
list of submitted synopses so that those interested in contributing to
the publication and being a co-author can signal their interest.
Substantial contributions are a requirement for co-authorships. All
potential co-authors must be involved early in the process of preparing
the publications, ideally at the stage of the synopsis submission. In
addition to the named authors, all papers should by default include the
group authorship of ‘on behalf of the DP-Next investigators’.

Author lists and orders may be amended after synopsis approval by
consensus among the authors or by the SC if the factual contributions
differ from those foreseen initially.

If disagreements about authorship cannot be resolved by consensus within
the author group, the SC will make a decision. Regardless of named
authors, publications will include detailed contributor lists along with
described contributions as per the CRediT roles, either directly in the
paper, as a supplemental appendix, or described on an external publicly
accessible document. The SC will ensure that such a document is publicly
accessible and up to date. Furthermore, papers must include an
acknowledgment to external parties such as funders, institutions,
participants and service providers that have contributed to the specific
work presented in each paper. The SC will maintain an updated
acknowledgment statement for the DP-Next project.

## Practical implementation

### Initiative for publications

It is expected that the initiative to propose a new publication based on
DP-Next data will primarily be taken by investigators within the DP-Next
team. However, DP-Next also welcomes collaborative publication
initiatives by external investigators (i.e. those who are not part of
the DP-Next team). Publication initiatives led by external investigators
must include at least one co-author from the DP-Next team to ensure
continuity and handling and reporting according to DP-Next guidelines.
Publication initiatives can be stand-alone or part of a wider protocol,
such as a PhD or post-doc protocol. The same steps outlined below for
manuscripts apply if DP-Next results are to be included in a PhD thesis.

### Steps to follow during the publication life cycle

The requirements for preparing a DP-Next publication apply to both
internal and external researchers and should follow these steps:

1. Creation of a publicly accessible repository specifically for each
   publication on Github. The repository should be placed under the
   DP-Next organization, be named according to the naming guide \[INSERT
   LINK TO NAMING GUIDE\] and preferably use the Seedcase template
   \[INSERT LINK TO TEMPLATE\]. This repository will contain the various
   'sub-products' described below as separate 'chapters'.

2. Synopsis preparation and approval from the SC. This should take place
   as early as possible, and should be completed before any part of the
   analysis or writing process starts. The synopsis should be brief
   (around 1 page) and be written inside the Github repository created
   under 1, according to this template \[ADD LINK TO TEMPLATE\]. It
   should contain:

   - A link to the Github repository

   - The title

   - The proposed author list, with roles

   - A clear hypothesis, with a brief background if needed

   - The required DP-Next data

   - A general outline of the analytical approach

   - A proposed timeline for the work, including proposed conference presentations and proposed target journals

   - Connection to specific DP-Next WP aims, PhD/postdoc protocols and other prior or ongoing projects

   - A table to track the status of the project with dates as it progresses through the cycle

   Once the synopsis is completed, an approval request should be
   submitted to the SC by filing an 'issue' in the Github wp1-management
   project, with reference to the publication's Github repository. The
   Steering Committee will review and discuss requests within the Github
   environment or at their regular meetings, and may provide comments
   and ask for changes before approval. The synopsis is an internal
   management document and does not need to be published on Zenodo.

3. For investigators [not]{.underline} covered by the DP-Next agreements
   (by institutional affiliation to one of the Steno Diabetes Centres),
   a separate data agreement must be signed if they require data access.
   This agreement must be in place before any data access can be given.

4. Protocol writing. It is expected that the first output from each
   publication will be an analysis protocol. Investigators should follow
   these steps:

   - Draft a detailed analysis protocol in the publication's Github repository that describes the following points:
     - The title
     - Authors
     - Background and hypothesis
     - Description of the data that will be used specifically for this publication
     - Description of the specific data analysis plan for this publication
   - Once there is a solid version, the protocol should be published on an online repository such as Zenodo or OpenAIRE to obtain a Digital Object Identifier (DOI) and clearly establish a clear temporal sequence between definition of hypotheses/analytic approaches and analysis of data.
   - If new versions of the protocol are generated as the project advances, updates should also be pushed to Zenodo / OpenAIRE. This can be set up automatically using the Seedcase template.
   - A stable version of the protocol may also be published as a preprint on online preprint servers such as arXiv or medRxiv.

5. Work on the data analysis. Depending on the data used, this work will
   take place on a local secure server or on Denmark Statistics Servers.
   Please follow the guides on the use of Git / Github for data analysis
   in these two environments, making sure that the analytical code is
   saved in the project's Github repository.

6. Preparation of a conference abstract, interim / preliminary results /
   progress reports / presentations / slides. As the project progresses,
   various interim results and materials are likely to be produced. As
   far as possible, these should also be managed as separate 'chapters'
   of the project's Github repository.

7. Preparation of the manuscript. This should also take place as a
   'chapter' in the project's Github repository and should be clearly
   linked to the annotated detailed analytical code that generated the
   tables, graphs and figures included in the manuscript. Stable
   versions of the manuscript should be published as a preprint on
   online preprint servers such as arXiv or medRxiv.

8. Internal approval and first submission. When a substantial version of
   the manuscript / a conference abstract is ready for submission, the
   authors should request approval for submission from the SC by filing
   an 'issue' in the Github wp1-management project, with reference to
   the publication's Github repository. This should be done at least two
   weeks before the intended submission date / deadline. The SC will
   provide their agreement /disagreement as soon as possible and within
   two weeks. The SC will only disagree with the submission of a paper
   or abstract at this stage if it is felt to be too premature, is seen
   as repetition of previously published work or if substantial parts of
   the process described in this guideline have not been followed (e.g.
   no Github repository, no approved synopsis, no protocol).

9. Updates and acceptance. Throughout the project life cycle (also after
   the manuscript / conference abstract is submitted), the authors
   should keep the status table in the synopsis up to date to reflect
   (where relevant):

   - Major milestones in analysis / writing / internal review, linked to major versions.

   - SC approval

   - First submission

   - Rejections / resubmission

   - Revisions / resubmission

   - Acceptance

10. Publication. The authors should send a copy of the full text of a
    publication and/or a link to the final materials to the SC and
    report/log the activity on the relevant academic output tracking
    platform (e.g. ResearchFish).

### Other forms of dissemination

Other forms of dissemination include: keynotes, invited talks, press
releases, media appearances, podcasts, posts on social media or outreach
activities. In general, dissemination activities must never interfere
with or weaken the opportunities for academic publication of the study
results.

#### Dissemination of new results

The following applies if the dissemination contains any 'new results'
from DP-Next. 'New results' refers to any results that have not yet been
definitively published in a peer-reviewed journal. Results included in a
conference abstract/presentation, preprint or Github repository are
still considered new results until they are definitively published.

- Inclusion of preliminary or new results in lectures/seminars being
  given outside the research teams directly involved in DP-Next, should
  be done with care. Researchers wishing to present preliminary or new
  results in small academic circles should notify the SC before giving
  the presentation, by raising an issue in the project's Github.

- Dissemination of new results through media or outreach activities can
  only take place after the academic dissemination in the form of
  published conference abstracts or presentations. In the case of a
  press release issued in connection with a conference, the
  dissemination can be prepared ahead of time under a time embargo that
  coincides with the academic presentation of results.

- Before issuing any press release or disseminating any new results from
  DP-Next, researchers should inform the SC.

- For press releases the notification should occur as early as possible,
  and if there is less than 72 hours for approval, e-mail can be
  followed up with text message or phone call to the PI or other members
  of the SC.

- After the dissemination activity, the researcher should send a copy or
  link to the final materials to the SC and report/log the activity on
  the relevant academic output tracking platform (e.g. Researchfish).

#### Dissemination of published results / general DP-Next dissemination

If a dissemination activity only covers general information about
DP-Next or definitively published results (i.e. not including
preliminary results, preprints, conference abstracts or Github content),
prior approval by the SC is not required. It is highly appreciated if
the researcher keeps the SC and the relevant members of the team updated
on any major dissemination activities. The researcher should still send
a copy or link to the final materials to the SC and report/log the
activity on the relevant academic output tracking platform (e.g.
ResearchFish).

### Steering Committee

The Steering Committee consists of the following members:

- Daniel Witte, SDCA
- Gunnar Toft, SDCA
- Clause Bogh Juhl, SDCO
- Stine Byberg, SDCC
- Nicklas Rasmussen, SDCN
- Line Lindahl-Jacobsen, SDCS
- Maria Skaalum SDCF
- Marit Eika Jørgensen, SDCG

The Steering Committee meets regularly online, at least 6 times per year
and communicates more frequently as required.

### Acknowledgement Statement

Any publication, dissemination or communication stemming from the
DP-Next project should mention the following acknowledgment statement
(version 12-03-2025):

"The DP-Next project was funded by a Steno National Collaborative Grant
from the Novo Nordisk Foundation (Grant number XXXX \[Look up and
complete\]). Additional funding was obtained from all Steno Diabetes
Centers. The WP3 electronic questionnaires were distributed using OPEN
Research Infrastructure at Steno Diabetes Center Odense."
