# Overview {#sec-overview}

## Academia lags far behind industry in many practical ways

Science, while pursuing cutting edge knowledge, lags far behind industry
in standard operational, organisational, and technological practices,
tools, and methods. For example, there are nearly no research software
or data engineers within research groups or institutions, even though
software and data are foundational components to conducting research in
the modern era.

Traditional management of larger scale research projects often involves
setting up steering committees who check on progress through status
updates and discuss solutions to issues that arise. However, there are
many modern tools and methods used within industry that research
environments and projects could benefit from, such as data engineering,
software development, and operations management.

Likewise, basic modern communication and project management tools are
rarely, if ever, used within research environments, even though they are
standard practice in many corporate settings. If these things are used
by some groups, they are not shared nor advertised through traditional
scientific publications, so if they exist, others can't reuse and learn
from each other to improve how we do research.

## Challenges and barriers in academia

Aside from the standard project management tasks, implementing modern
research operations and collaborative practices that support conducting
open and reproducible science across multiple institutions (such as all
the Steno Centers in Denmark) will be a major challenge. From both the
technical and cultural sides, these work tasks often lack support at the
institutional level and lack of awareness and training at the personnel
level. So usually work is done from the ground-up, which often results
in unexpected issues.

Given that there are few personnel in research environments with the
necessary technical knowledge and skills, and they often move from
academia into industry positions, a substantial amount of time and
effort must be spent in training and upskilling existing personnel. The
reason we’ve structured the groups to include at least one "tech lead"
who is also part of the technical working group is to help minimise this
challenge. We aim to provide training to these tech leads by embedding
them in some of the work we are doing at Steno Aarhus, where we have
been implementing many of these practices.

Another major challenge will be coordinating tasks and work between IT
systems that often don’t work well together or are suboptimally designed
for cross-institution collaboration. This is one reason we've decided to
establish the technical working group, so that we can minimise the
impact these issues have on completing the project deliverables.

## Science needs more team-based, collaborative approaches

Science is also increasingly moving into more team-based, multi-centered
enterprises, as well as having a greater requirement for openness and
reproducibility. These require using modern practices designed for these
conditions, rarely seen in academia but common within many industry
settings.

Ultimately, academia needs to recognize and incorporate these practices
in order to stay relevant and competitive in the modern research
landscape. But we need more funds, support, awareness, and training to
make this happen.

This is what Work Package 1 aims to help address.
