name: Add to project board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
  pull_request:
    types:
      - reopened
      - opened

# Improve security by limiting permissions.
permissions: read-all

jobs:
  add-to-project:
    uses: dp-next/.github/.github/workflows/reusable-add-to-project.yml@main
    # Set at job level for where it is needed.
    permissions:
      pull-requests: write
    with:
      board-number: 9
    secrets:
      add-to-board-token: ${{ secrets.ADD_TO_BOARD }}
      gh-token: ${{ secrets.GITHUB_TOKEN }}
