name: Build and deploy website

on:
  push:
    branches: main

# you need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write

jobs:
  build-deploy-docs:
    uses: dp-next/.github/.github/workflows/reusable-build-website.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
