name: Sync with repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Limit permissions to improve security.
permissions: read-all

jobs:
  sync:
    uses: seedcase-project/.github/.github/workflows/reusable-sync-files.yml@main
    with:
      app-id: ${{ vars.SYNC_FILES_APP_ID }}
    secrets:
      sync-files-token: ${{ secrets.SYNC_FILES_TOKEN }}
